"""change Picture url to int

Revision ID: 4bbd5c6d1047
Revises: 41390fc5fc77
Create Date: 2021-06-08 10:36:48.631025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bbd5c6d1047'
down_revision = '41390fc5fc77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avatar', sa.Column('img_id', sa.Integer(), nullable=True))
    op.drop_column('avatar', 'url')
    op.add_column('picture', sa.Column('img_id', sa.Integer(), nullable=True))
    op.drop_column('picture', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('picture', 'img_id')
    op.add_column('avatar', sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('avatar', 'img_id')
    # ### end Alembic commands ###
