"""email activation checker for user

Revision ID: 5066f0f12ca3
Revises: b598103ab0e9
Create Date: 2021-06-04 00:23:53.344548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5066f0f12ca3'
down_revision = 'b598103ab0e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_activated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_activated')
    # ### end Alembic commands ###
