"""change payment fields

Revision ID: 6cda7fd9dc05
Revises: 81eae5350bd3
Create Date: 2021-05-25 00:01:11.253731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cda7fd9dc05'
down_revision = '81eae5350bd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('card_id', sa.Integer(), nullable=False))
    op.add_column('payment', sa.Column('credentials', sa.String(length=8000), nullable=True))
    op.drop_column('payment', 'card_number')
    op.drop_column('payment', 'is_valid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('is_valid', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('payment', sa.Column('card_number', sa.VARCHAR(length=14), autoincrement=False, nullable=False))
    op.drop_column('payment', 'credentials')
    op.drop_column('payment', 'card_id')
    # ### end Alembic commands ###
