"""update user, avatar table

Revision ID: 83e2011bc0c2
Revises: 4bbd5c6d1047
Create Date: 2021-06-08 11:21:37.257665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83e2011bc0c2'
down_revision = '4bbd5c6d1047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avatar', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'avatar', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'avatar', type_='foreignkey')
    op.drop_column('avatar', 'user_id')
    # ### end Alembic commands ###
