"""nullable true

Revision ID: d25b8b28c1ba
Revises: 2fd877406fa3
Create Date: 2021-05-29 01:00:05.459169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd25b8b28c1ba'
down_revision = '2fd877406fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'finished_reading',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('review', 'started_reading',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'started_reading',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('review', 'finished_reading',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
